const STATUSES = {
  UNSOLVED: 'UNSOLVED',
  SIGNEDOUT: 'SIGNEDOUT',
  UNVERIFIED: 'UNVERIFIED',
  SIGNEDIN: 'SIGNEDIN'
};

const EVENTS = {
  AUTH_MECH_CREATED: 'EVENTS.AUTH_MECH_CREATED',
  AUTH_SERVICE_UPDATED: 'EVENTS.AUTH_SERVICE_UPDATED',
  FUSE_SERVICE_UPDATED: 'EVENTS.FUSE_SERVICE_UPDATED',
  PASSWORD_UPDATED: 'EVENTS.PASSWORD_UPDATED',
  AUTH_STATE_CHANGED: 'EVENTS.AUTH_STATE_CHANGED'
};

export { EVENTS, STATUSES };
