const STATUSES = {
  UNSOLVED: 'UNSOLVED',
  SIGNEDOUT: 'SIGNEDOUT',
  UNVERIFIED: 'UNVERIFIED',
  SIGNEDIN: 'SIGNEDIN'
};

const EVENTS = {
  AUTH_MECH_CREATED: 'EVENTS.AUTH_MECH_CREATED',
  USER_SIGNEDOUT: 'EVENTS.USER_SIGNEDOUT',
  PASSWORD_UPDATED: 'EVENTS.PASSWORD_UPDATED',
  UNFUSED_USER_SIGNEDIN: 'EVENTS.UNFUSED_USER_SIGNEDIN',
  FUSED_USER_SIGNEDIN_OR_UPDATED: 'EVENTS.FUSED_USER_SIGNEDIN_OR_UPDATED',
  AUTH_STATE_CHANGED: 'EVENTS.AUTH_STATE_CHANGED'
};

export { EVENTS, STATUSES };
