const STATUSES = {
  UNSOLVED: 'UNSOLVED',
  SIGNEDOUT: 'SIGNEDOUT',
  PENDING: 'PENDING',
  SIGNEDIN: 'SIGNEDIN'
};

const EVENTS = {
  AUTH_MECH_CREATED: 'EVENTS.AUTH_MECH_CREATED',
  USER_SIGNEDOUT: 'EVENTS.USER_SIGNEDOUT',
  USER_SIGNEDIN: 'EVENTS.USER_SIGNEDIN',
  UNVERIFIED_USER_SIGNEDIN: 'EVENTS.UNVERIFIED_USER_SIGNEDIN',
  PASSWORD_UPDATED: 'EVENTS.PASSWORD_UPDATED'
};

export { EVENTS, STATUSES };
